spring:
  application:
    name: Todo-App
  
  # application.properties
server:
  port: ${PORT:3333}

  # Optional: Add some basic logging configuration
logging:
  level:
    com.example.todoapp: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"